version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: jobfit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jobfit_ai
      MYSQL_USER: jobfit
      MYSQL_PASSWORD: jobfitpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jobfit-network
    restart: unless-stopped

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobfit-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jobfit_ai?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: jobfit
      SPRING_DATASOURCE_PASSWORD: jobfitpassword
      JWT_SECRET: jobfit-ai-secret-key-2024-very-long-and-secure-key-for-production
      JWT_EXPIRATION: 86400000
      HUGGINGFACE_API_TOKEN: your-huggingface-token-here
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - jobfit-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jobfit-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - jobfit-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: jobfit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - jobfit-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  jobfit-network:
    driver: bridge 